runtime: nodejs20
env: standard

instance_class: F1

automatic_scaling:
  min_instances: 0
  max_instances: 1

resources:
  cpu: 1
  memory_gb: 1

env_variables:
  DB_NAME: luma
  DB_HOST: rds-mysql-distrisuper.cvigiku0yimh.us-east-1.rds.amazonaws.com
  DB_PASSWORD: '%distriApi123%'
  DB_PORT: '3306'
  DB_USER: distriap_luma
  URL_ERP_API_MORPHI: https://api.morphi.net/
  ERP_API_USERNAME: t4fcyp
  ERP_API_PASSWORD: po890d8wzq
  ERP_API_GRUPO: 159
  ERP_API_ALIAS: 'LUMA BAR'

service_account: luma-api-482115@appspot.gserviceaccount.com
